### THERMAL CONTROLLER CONSTANTS
SENSOR_WIDTH: int = 256
SENSOR_HEIGHT: int = 192
DEVICE_FPS: int = 25
DEVICE_NAME: str = "TS001"

### DEFAULT CALCULATED VALUES
TEMPERATURE = 0
TEMPERATURE_RAW = 0
TEMPERATURE_MIN = 0
TEMPERATURE_MAX = 0
TEMPERATURE_AVG = 0
TEMPERATURE_SIG_DIGITS = 2